# config.yaml
model:
  num_classes: 1
  nChannel: 100
  backbone: resnet50
  pretrained: True
  architecture: Crack-Segmenter-v2
  use_dice: True
  use_bce: True
  baseline: False
  
training:
  batch_size: 4
  num_epochs: 500
  learning_rate: 0.0001
  weight_decay: 0.00001
  early_stopping_patience: 50

data:
  image_size: 448
  root_dir: '/path/to/dataset/root/dir'
  dataset_name: 'crack500'
  num_workers: 4

utils:
  save_dir: 'path/to/trained_models'
