# Example configuration for CrackSegmenter model training
# Set baseline=False to use CrackSegmenter architectures

model:
  num_classes: 1
  nChannel: 100
  backbone: resnet18
  pretrained: True
  use_cbam: True
  use_transformer: True
  architecture: Crack-Segmenter-v2  # Options: Crack-Segmenter, Crack-Segmenter-v0, Crack-Segmenter-v1, Crack-Segmenter-v2, Crack-Segmenter-v3
  use_dice: True
  use_bce: True
  baseline: False  # Set to False for CrackSegmenter models
  
training:
  batch_size: 4
  num_epochs: 500
  learning_rate: 0.0001
  weight_decay: 0.00001
  early_stopping_patience: 50

data:
  image_size: 448
  root_dir: '/path/to/your/dataset'
  dataset_name: 'cracktree200'  # Options: cracktree200, cfd, forest, gaps_384
  num_workers: 4
  mask_ext: '.png'

utils:
  save_dir: './trained_models/cracksegmenter'
