# config.yaml
model:
  num_classes: 1
  nChannel: 100
  backbone: resnet18
  pretrained: True
  use_cbam: True
  use_transformer: True
  architecture: MSFormer_v2
  use_dice: True
  use_bce: True
  baseline: False
  
training:
  batch_size: 4
  num_epochs: 500
  learning_rate: 0.0001
  weight_decay: 0.00001
  early_stopping_patience: 50

data:
  image_size: 448
  root_dir: '/mmfs1/projects/armstrong.aboah/Pavement-distress-segmentation/Public-Datasets'
  dataset_name: 'forest'
  num_workers: 4
  mask_ext: '.png'

utils:
  save_dir: '/mmfs1/projects/armstrong.aboah/Pavement-distress-segmentation/trained_models'